# Generated by Django 4.0.5 on 2022-06-11 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('realizacao', models.CharField(max_length=9)),
                ('topicos', models.CharField(max_length=500)),
                ('pagCadeira', models.CharField(max_length=200)),
                ('ects', models.IntegerField()),
                ('classicicacao', models.IntegerField()),
                ('ano', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Colega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('linkedin', models.CharField(max_length=200)),
                ('pagAPP', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('texto', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('pontuacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=20)),
                ('data', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('linkedin', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=5)),
                ('titulo', models.CharField(max_length=50)),
                ('resumo', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='')),
                ('relatorio', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('video', models.CharField(max_length=200)),
                ('autores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.colega')),
                ('orientadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='')),
                ('realizacao', models.DateField()),
                ('github', models.CharField(max_length=200)),
                ('youtube', models.CharField(max_length=200)),
                ('tecnologias', models.CharField(max_length=200)),
                ('competencias', models.CharField(max_length=200)),
                ('cadeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.cadeira')),
                ('participantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.colega')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='pofessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor'),
        ),
    ]
