# Generated by Django 4.0.4 on 2022-05-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('ects', models.IntegerField()),
                ('realizacao', models.CharField(max_length=9)),
                ('topicos', models.CharField(max_length=500)),
                ('pofessor', models.CharField(max_length=25)),
            ],
        ),
    ]
