# Generated by Django 4.0.5 on 2022-06-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='relatorio',
            field=models.CharField(max_length=400),
        ),
    ]
