# Generated by Django 4.0.4 on 2022-05-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_cadeira_delete_cadeiras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=500)),
                ('imagem', models.ImageField(upload_to='')),
                ('realizacao', models.DateTimeField()),
                ('participantes', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=200)),
                ('youtube', models.CharField(max_length=200)),
                ('tecnologias', models.CharField(max_length=200)),
                ('competencias', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='pagCadeira',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
