# Generated by Django 4.0.4 on 2022-05-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projeto_cadeira_pagcadeira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('linkedin', models.CharField(max_length=200)),
                ('pagAPP', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('linkedin', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='cadeira',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.cadeira'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projeto',
            name='realizacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='participantes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.colega'),
        ),
    ]
